# Generated by Django 4.1 on 2022-08-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductDescription', models.CharField(max_length=500)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('PhotoFileName', models.CharField(max_length=200)),
            ],
        ),
    ]
